apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  image: kindest/node:v1.21.1
  extraPortMappings:
  - containerPort: 30443
    hostPort: 443
networking:
  podSubnet: 10.1.0.0/16
  serviceSubnet: 10.96.0.1/12
