apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: kind
  namespace: garden-dev
spec:
  secretBindingName: my-provider-account
  cloudProfileName: kind
  region: local
  provider:
    type: kind
    infrastructureConfig:
      apiVersion: kind.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
    controlPlaneConfig:
      apiVersion: kind.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
    workers:
    - name: cpu-worker
      minimum: 1
      maximum: 1
      maxSurge: 1
      maxUnavailable: 0
      kubernetes:
        kubelet:
          failSwapOn: false
      machine:
        type: kind-node
        image:
          name: gardenlinux
      cri:
        name: containerd
      volume:
        type: standard
        size: 20Gi
      zones:
      - local-home
  seedName: my-seed
  kubernetes:
    version: "1.21"
    allowPrivilegedContainers: true
  hibernation:
    enabled: false
  networking:
    type: calico
    pods: 10.77.0.0/16
    services: 10.78.0.0/16
#    nodes: 10.76.0.0/16
  maintenance:
    timeWindow:
      begin: 220000+0100
      end: 230000+0100
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: true
  addons:
    nginxIngress:
      enabled: false
    kubernetesDashboard:
      enabled: false
