apiVersion: core.gardener.cloud/v1beta1
kind: CloudProfile
metadata:
  name: kind
spec:
  kubernetes:
    versions:
    - classification: supported
      version: 1.21.5
  machineImages:
  - name: gardenlinux
    versions:
    - classification: supported
      cri:
      - name: containerd
      version: 318.9.0
  machineTypes:
  - cpu: "1"
    gpu: "0"
    memory: 1Gi
    name: kind-node
    usable: true
  regions:
  - name: local
    zones:
    - name: local-home
  type: kind
  volumeTypes:
  - class: standard
    name: standard
    usable: true
