apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: seed-secret
    namespace: garden
    files:
      - kubeconfig
  - name: my-provider-account
    namespace: garden-dev
    literals:
      - foo=bar

resources:
  - project.yaml
  - secret-internal-domain.yaml
  - cloudprofile.yaml
  - https://raw.githubusercontent.com/gardener/gardener-extension-os-ubuntu/v1.13.0/example/controller-registration.yaml
  - https://raw.githubusercontent.com/gardener/gardener-extension-os-gardenlinux/v0.10.0/example/controller-registration.yaml
  - https://raw.githubusercontent.com/gardener/gardener-extension-networking-calico/v1.20.1/example/controller-registration.yaml
  - controller-registration.yaml
  - seed.yaml
  - secretbinding.yaml
