# Project objects logically group team members, secrets, and Shoot clusters. They result in Kubernetes namespaces
# prefixed with "garden-".
---
apiVersion: core.gardener.cloud/v1beta1
kind: Project
metadata:
  name: dev
spec:
  owner:
    apiGroup: rbac.authorization.k8s.io
    kind: User
    name: john.doe@example.com
  namespace: garden-dev
