---
apiVersion: v1
kind: Secret
metadata:
  name: internal-domain-example-com
  namespace: garden
  labels:
    gardener.cloud/role: internal-domain
  annotations:
    dns.gardener.cloud/provider: aws-route53
    dns.gardener.cloud/domain: example.com
type: Opaque
data: {}
