apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: local-dev
  namespace: garden-dev
spec:
  secretBindingName: my-provider-account
  cloudProfileName: kind
  region: local
  provider:
    type: kind
    infrastructureConfig:
      apiVersion: kind.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
    controlPlaneConfig:
      apiVersion: kind.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
  kubernetes:
    version: "1.21"
    allowPrivilegedContainers: true
  hibernation:
    enabled: false
  networking:
    type: calico
    pods: 100.96.0.0/11
    nodes: 10.250.0.0/16
    services: 100.64.0.0/13
  maintenance:
    timeWindow:
      begin: 220000+0100
      end: 230000+0100
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: true
  addons:
    nginxIngress:
      enabled: false
    kubernetesDashboard:
      enabled: false
