apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: provider-kind
type: helm
providerConfig:
  values:
    fullnameOverride: provider-kind
    controllerManager:
      replicas: 0
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: provider-kind
spec:
  deployment:
    policy: Always
