apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: provider-kind
type: helm
providerConfig:
  values:
    fullnameOverride: provider-kind
    controllerManager:
      replicas: 0
