apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gardener-extension-provider-kind.fullname" . }}-controller-manager
  labels:
  {{- include "gardener-extension-provider-kind.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gardener-extension-provider-kind.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
  {{- include "gardener-extension-provider-kind.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "gardener-extension-provider-kind.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "gardener-extension-provider-kind.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - --leader-elect
        - --node-image github.com/adracus/gardener-extension-provider-kind/node:latest
        command:
        - /manager
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10
          }}
        securityContext:
          allowPrivilegeEscalation: false
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: {{ .Values.controllerManager.kubeRbacProxy.image.repository }}:{{ .Values.controllerManager.kubeRbacProxy.image.tag
          | default .Chart.AppVersion }}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
        resources: {}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "gardener-extension-provider-kind.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10