apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gardener-extension-provider-kind.fullname" . }}-metrics-reader
  labels:
  {{- include "gardener-extension-provider-kind.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get