apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default

images:
  - name: controller
    newName: ghcr.io/adracus/gardener-extension-provider-kind/controller
    newTag: latest

patchesStrategicMerge:
  - patch-manager-node-image.yaml
