apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          args:
            - --leader-elect
            - --node-image github.com/adracus/gardener-extension-provider-kind/node:latest
